### ISSUE TITLE
reporte de visual Studio UX UI

### ISSUE THREAD

**Issue by JORGELUIS2266** [SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-equipo-kem#1]
[REPORTE-VISUAL STUDIO Studio UX UI.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-equipo-kem/files/14335842/REPORTE-VISUAL.STUDIO.Studio.UX.UI.pdf)

**Comment by josealfredo79** [comment]
Calificacion 19 bien hecho y revisado...
